
# templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ml-algorithm-api.fullname" . }}
  labels:
    app: {{ include "ml-algorithm-api.name" . }}
spec:
  rules: