# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ml-algorithm-api.fullname" . }}
  labels:
    app: {{ include "ml-algorithm-api.name" . }}
spec:
  selector:
    app: {{ include "ml-algorithm-api.name" . }}
  type: {{ .Values.service.type }}
  ports:
    - name: https
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      # add your SSL/TLS configuration here
      tls:
        certKey: tls.crt
        cert: |-
          {{ .Files.Get "tls.crt" | b64enc }}
        key: |-
          {{ .Files.Get "tls.key" | b64enc }}
